package com.syngenta.sadie.agreportingrules.rules;

import java.util.List;

import com.syngenta.sadie.agreportingrules.model.UserInformation;
import com.syngenta.sadie.agreportingrules.model.LoanAmount;
import com.syngenta.sadie.agreportingrules.model.CollegeStatus;
import com.syngenta.sadie.agreportingrules.model.StateInformation;

/******************************************************************************
 * These are rules that should be written as practice.  The test cases are
 * set to @Ignore and therefore will not run by default.   Create the rules
 * as defined below and then remove the @Ignore annotation from the 
 * 'StateInformation.feature' file to test the rules that you created.
 ******************************************************************************/

/******************************************************************************
 * MD Specific Loan Rules
 * 
 *  RULE 1
 *  GIVEN the user is from MD and is one of the first N users to apply in order
 *        where N is the total number of loans available
 *  AND age >= 18
 *  AND collegeStatus == PartTime
 *  AND familyIncome <=80000
 *  THEN eligible for $10000 loan
 * 
 *  RULE 2
 *  GIVEN the user is from MD and is one of the first N users to apply in order
 *        where N is the total number of loans available
 *  AND age >= 18
 *  AND collegeStatus == FullTime
 *  AND familyIncome <=60000
 *  THEN eligible for $15000 loan
 *
 *  RULE 3
 *  GIVEN the user is from MD and is one of the first N users to apply in order
 *        where N is the total number of loans available
 *  AND age < 18
 *  AND collegeStatus == FullTime
 *  AND familyIncome <=60000
 *  THEN eligible for $20000 loan
 *
 *  RULE 4
 *  GIVEN the user is from MD and is one of the first N users to apply in order
 *        where N is the total number of loans available
 *  AND age < 18
 *  AND collegeStatus == PartTime
 *  AND familyIncome <=50000
 *  THEN eligible for $5000 loan
 ******************************************************************************/
